/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 16/05/2018 10:40:26
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLDSIFreq_Value                     500000000
#define MX_SYSCLKFreq_VALUE                     390000000
#define MX_HCLKFreq_Value                       195000000
#define MX_CortexFreq_Value                     390000000
#define MX_APB1Freq_Value                       97500000
#define MX_APB2Freq_Value                       97500000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        390000000
#define MX_WatchDogFreq_Value                   32000
#define MX_DSIFreq_Value                        96000000
#define MX_DSIPHYCLKFreq_Value                  96000000
#define MX_DSITXEscFreq_Value                   20000000
#define MX_SPDIFRXFreq_Value                    390000000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_MCO2PinFreq_Value                    390000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* DMA Configuration */

/* DMA DMA2_Stream2 */
#define MX_DMA2_Stream2_DMA_MemBurst            DMA_MBURST_SINGLE
#define MX_DMA2_Stream2_DMA_Instance            DMA2_Stream2
#define MX_DMA2_Stream2_DMA_FIFOMode            DMA_FIFOMODE_ENABLE
#define MX_DMA2_Stream2_DMA_Priority            DMA_PRIORITY_VERY_HIGH
#define MX_DMA2_Stream2_DMA_MemDataAlignment    DMA_MDATAALIGN_HALFWORD
#define MX_DMA2_Stream2_DMA_Mode                DMA_NORMAL
#define MX_DMA2_Stream2_DMA_SyncRequestNumber   1
#define MX_DMA2_Stream2_DMA_Request             DMA_REQUEST_MEM2MEM
#define MX_DMA2_Stream2_DMA_SyncPolarity        HAL_DMAMUX_SYNC_NO_EVENT
#define MX_DMA2_Stream2_DMA_Direction           DMA_MEMORY_TO_MEMORY
#define MX_DMA2_Stream2_DMA_PeriphBurst         DMA_PBURST_SINGLE
#define MX_DMA2_Stream2_DMA_SignalID            
#define MX_DMA2_Stream2_DMA_MemInc              DMA_MINC_ENABLE
#define MX_DMA2_Stream2_DMA_IpInstance          
#define MX_DMA2_Stream2_DMA_RequestNumber       1
#define MX_DMA2_Stream2_DMA_EventEnable         DISABLE
#define MX_DMA2_Stream2_DMA_SyncEnable          DISABLE
#define MX_DMA2_Stream2_DMA_DMA_Handle          
#define MX_DMA2_Stream2_DMA_PeriphDataAlignment DMA_PDATAALIGN_HALFWORD
#define MX_DMA2_Stream2_DMA_Polarity            HAL_DMAMUX_REQ_GEN_RISING
#define MX_DMA2_Stream2_DMA_SyncSignalID        
#define MX_DMA2_Stream2_DMA_PeriphInc           DMA_PINC_ENABLE
#define MX_DMA2_Stream2_DMA_FIFOThreshold       DMA_FIFO_THRESHOLD_FULL

/* NVIC Configuration */

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_FMC_D8_DA8_Pin                       PE11
#define MX_FMC_D8_DA8_GPIOx                     GPIOE
#define MX_FMC_D8_DA8_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D8_DA8_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D8_DA8_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_D8_DA8_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D8_DA8_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD14 */
#define MX_FMC_D0_DA0_Pin                       PD14
#define MX_FMC_D0_DA0_GPIOx                     GPIOD
#define MX_FMC_D0_DA0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D0_DA0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_DA0_GPIO_Pin                  GPIO_PIN_14
#define MX_FMC_D0_DA0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D0_DA0_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD12 */
#define MX_FMC_A17_ALE_Pin                      PD12
#define MX_FMC_A17_ALE_GPIOx                    GPIOD
#define MX_FMC_A17_ALE_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A17_ALE_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A17_ALE_GPIO_Pin                 GPIO_PIN_12
#define MX_FMC_A17_ALE_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PD6 */
#define MX_FMC_NWAIT_Pin                        PD6
#define MX_FMC_NWAIT_GPIOx                      GPIOD
#define MX_FMC_NWAIT_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_NWAIT_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWAIT_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_NWAIT_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_NWAIT_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE8 */
#define MX_FMC_D5_DA5_Pin                       PE8
#define MX_FMC_D5_DA5_GPIOx                     GPIOE
#define MX_FMC_D5_DA5_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D5_DA5_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_DA5_GPIO_Pin                  GPIO_PIN_8
#define MX_FMC_D5_DA5_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D5_DA5_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE13 */
#define MX_FMC_D10_DA10_Pin                     PE13
#define MX_FMC_D10_DA10_GPIOx                   GPIOE
#define MX_FMC_D10_DA10_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D10_DA10_GPIO_Pin                GPIO_PIN_13
#define MX_FMC_D10_DA10_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D10_DA10_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD1 */
#define MX_FMC_D3_DA3_Pin                       PD1
#define MX_FMC_D3_DA3_GPIOx                     GPIOD
#define MX_FMC_D3_DA3_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D3_DA3_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_DA3_GPIO_Pin                  GPIO_PIN_1
#define MX_FMC_D3_DA3_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D3_DA3_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_FMC_D13_DA13_Pin                     PD8
#define MX_FMC_D13_DA13_GPIOx                   GPIOD
#define MX_FMC_D13_DA13_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D13_DA13_GPIO_Pin                GPIO_PIN_8
#define MX_FMC_D13_DA13_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D13_DA13_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD9 */
#define MX_FMC_D14_DA14_Pin                     PD9
#define MX_FMC_D14_DA14_GPIOx                   GPIOD
#define MX_FMC_D14_DA14_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D14_DA14_GPIO_Pin                GPIO_PIN_9
#define MX_FMC_D14_DA14_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D14_DA14_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PD5 */
#define MX_FMC_NWE_Pin                          PD5
#define MX_FMC_NWE_GPIOx                        GPIOD
#define MX_FMC_NWE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NWE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NWE_GPIO_Pin                     GPIO_PIN_5
#define MX_FMC_NWE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NWE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE14 */
#define MX_FMC_D11_DA11_Pin                     PE14
#define MX_FMC_D11_DA11_GPIOx                   GPIOE
#define MX_FMC_D11_DA11_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D11_DA11_GPIO_Pin                GPIO_PIN_14
#define MX_FMC_D11_DA11_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D11_DA11_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE7 */
#define MX_FMC_D4_DA4_Pin                       PE7
#define MX_FMC_D4_DA4_GPIOx                     GPIOE
#define MX_FMC_D4_DA4_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D4_DA4_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_DA4_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_D4_DA4_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D4_DA4_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD11 */
#define MX_FMC_A16_CLE_Pin                      PD11
#define MX_FMC_A16_CLE_GPIOx                    GPIOD
#define MX_FMC_A16_CLE_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A16_CLE_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A16_CLE_GPIO_Pin                 GPIO_PIN_11
#define MX_FMC_A16_CLE_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PE15 */
#define MX_FMC_D12_DA12_Pin                     PE15
#define MX_FMC_D12_DA12_GPIOx                   GPIOE
#define MX_FMC_D12_DA12_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D12_DA12_GPIO_Pin                GPIO_PIN_15
#define MX_FMC_D12_DA12_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D12_DA12_GPIO_Mode               GPIO_MODE_AF_PP

/* Pin PE10 */
#define MX_FMC_D7_DA7_Pin                       PE10
#define MX_FMC_D7_DA7_GPIOx                     GPIOE
#define MX_FMC_D7_DA7_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D7_DA7_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_DA7_GPIO_Pin                  GPIO_PIN_10
#define MX_FMC_D7_DA7_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D7_DA7_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD15 */
#define MX_FMC_D1_DA1_Pin                       PD15
#define MX_FMC_D1_DA1_GPIOx                     GPIOD
#define MX_FMC_D1_DA1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D1_DA1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_DA1_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_D1_DA1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D1_DA1_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD4 */
#define MX_FMC_NOE_Pin                          PD4
#define MX_FMC_NOE_GPIOx                        GPIOD
#define MX_FMC_NOE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NOE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NOE_GPIO_Pin                     GPIO_PIN_4
#define MX_FMC_NOE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NOE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PE12 */
#define MX_FMC_D9_DA9_Pin                       PE12
#define MX_FMC_D9_DA9_GPIOx                     GPIOE
#define MX_FMC_D9_DA9_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D9_DA9_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D9_DA9_GPIO_Pin                  GPIO_PIN_12
#define MX_FMC_D9_DA9_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D9_DA9_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE9 */
#define MX_FMC_D6_DA6_Pin                       PE9
#define MX_FMC_D6_DA6_GPIOx                     GPIOE
#define MX_FMC_D6_DA6_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D6_DA6_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_DA6_GPIO_Pin                  GPIO_PIN_9
#define MX_FMC_D6_DA6_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D6_DA6_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD0 */
#define MX_FMC_D2_DA2_Pin                       PD0
#define MX_FMC_D2_DA2_GPIOx                     GPIOD
#define MX_FMC_D2_DA2_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D2_DA2_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_DA2_GPIO_Pin                  GPIO_PIN_0
#define MX_FMC_D2_DA2_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D2_DA2_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PG9 */
#define MX_FMC_NCE_Pin                          PG9
#define MX_FMC_NCE_GPIOx                        GPIOG
#define MX_FMC_NCE_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_NCE_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NCE_GPIO_Pin                     GPIO_PIN_9
#define MX_FMC_NCE_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_NCE_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PD10 */
#define MX_FMC_D15_DA15_Pin                     PD10
#define MX_FMC_D15_DA15_GPIOx                   GPIOD
#define MX_FMC_D15_DA15_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D15_DA15_GPIO_Pin                GPIO_PIN_10
#define MX_FMC_D15_DA15_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D15_DA15_GPIO_Mode               GPIO_MODE_AF_PP

/*-------------------------------- MDMA       --------------------------------*/

#define MX_MDMA                                 1

/* NVIC Configuration */

/* NVIC MDMA_IRQn */
#define MX_MDMA_IRQn_interruptPremptionPriority 0
#define MX_MDMA_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_MDMA_IRQn_Subriority                 0

/*-------------------------------- QUADSPI    --------------------------------*/

#define MX_QUADSPI                              1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_QUADSPI_CLK_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_CLK_Pin                      PF10
#define MX_QUADSPI_CLK_GPIOx                    GPIOF
#define MX_QUADSPI_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_QUADSPI_CLK_GPIO_Pin                 GPIO_PIN_10
#define MX_QUADSPI_CLK_GPIO_AF                  GPIO_AF9_QUADSPI
#define MX_QUADSPI_CLK_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PB6 */
#define MX_QUADSPI_BK1_NCS_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_NCS_GPIO_FM6             __NULL
#define MX_QUADSPI_BK1_NCS_Pin                  PB6
#define MX_QUADSPI_BK1_NCS_GPIOx                GPIOB
#define MX_QUADSPI_BK1_NCS_GPIO_PuPd            GPIO_PULLUP
#define MX_QUADSPI_BK1_NCS_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_NCS_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_NCS_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF6 */
#define MX_QUADSPI_BK1_IO3_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO3_Pin                  PF6
#define MX_QUADSPI_BK1_IO3_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO3_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO3_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_IO3_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO3_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF7 */
#define MX_QUADSPI_BK1_IO2_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO2_Pin                  PF7
#define MX_QUADSPI_BK1_IO2_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO2_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO2_GPIO_Pin             GPIO_PIN_7
#define MX_QUADSPI_BK1_IO2_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO2_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF9 */
#define MX_QUADSPI_BK1_IO1_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO1_Pin                  PF9
#define MX_QUADSPI_BK1_IO1_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO1_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO1_GPIO_Pin             GPIO_PIN_9
#define MX_QUADSPI_BK1_IO1_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO1_GPIO_Mode            GPIO_MODE_AF_PP

/* Pin PF8 */
#define MX_QUADSPI_BK1_IO0_GPIO_Speed           GPIO_SPEED_FREQ_VERY_HIGH
#define MX_QUADSPI_BK1_IO0_Pin                  PF8
#define MX_QUADSPI_BK1_IO0_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO0_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO0_GPIO_Pin             GPIO_PIN_8
#define MX_QUADSPI_BK1_IO0_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO0_GPIO_Mode            GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA MDMA_Channel0_QUADSPI_FIFO_TH_0 */
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_MaskAddress 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Instance MDMA_Channel0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_TransferTriggerMode MDMA_BUFFER_TRANSFER
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceDataSize MDMA_SRC_DATASIZE_HALFWORD
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestBurst MDMA_DEST_BURST_SINGLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestBlockAddressOffset 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_pNewNode 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestDataSize MDMA_DEST_DATASIZE_BYTE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Endianness MDMA_LITTLE_ENDIANNESS_PRESERVE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DMA_Handle 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceInc MDMA_SRC_INC_HALFWORD
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BlockCount 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DstAddress 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DataAlignment MDMA_DATAALIGN_PACKENABLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BlockDataLength 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_BufferTransferLength 16
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_DestinationInc MDMA_DEST_INC_DISABLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceBurst MDMA_SOURCE_BURST_SINGLE
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Priority MDMA_PRIORITY_HIGH
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Request MDMA_REQUEST_QUADSPI_FIFO_TH
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_Rank First
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_MaskData 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_IpInstance 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_CircularMode MDMA_LINEAR_LIST
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_node 
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SourceBlockAddressOffset 0
#define MX_MDMA_Channel0_QUADSPI_FIFO_TH_0_DMA_SrcAddress 0

/* NVIC Configuration */

/* NVIC QUADSPI_IRQn */
#define MX_QUADSPI_IRQn_interruptPremptionPriority 0
#define MX_QUADSPI_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_QUADSPI_IRQn_Subriority              0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14

/* Pin PB3 */
#define MX_SYS_JTDO-SWO_Pin                     PB3

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* Pin PB10 */
#define MX_S_TIM2_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM2_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM2_CH3_Pin                       PB10
#define MX_S_TIM2_CH3_GPIOx                     GPIOB
#define MX_S_TIM2_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM2_CH3_GPIO_Pin                  GPIO_PIN_10
#define MX_S_TIM2_CH3_GPIO_AF                   GPIO_AF1_TIM2

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PA11 */
#define MX_UART4_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_RX_Pin                         PA11
#define MX_UART4_RX_GPIOx                       GPIOA
#define MX_UART4_RX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_11
#define MX_UART4_RX_GPIO_AF                     GPIO_AF6_UART4

/* Pin PA12 */
#define MX_UART4_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Pin                         PA12
#define MX_UART4_TX_GPIOx                       GPIOA
#define MX_UART4_TX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART4_TX_GPIO_AF                     GPIO_AF6_UART4

/* DMA Configuration */

/* DMA UART4_RX */
#define MX_UART4_RX_DMA_Instance                DMA1_Stream0
#define MX_UART4_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_RX_DMA_Priority                DMA_PRIORITY_MEDIUM
#define MX_UART4_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_RX_DMA_SyncRequestNumber       1
#define MX_UART4_RX_DMA_Request                 DMA_REQUEST_UART4_RX
#define MX_UART4_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART4_RX_DMA_SignalID                
#define MX_UART4_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_RX_DMA_IpInstance              
#define MX_UART4_RX_DMA_RequestNumber           1
#define MX_UART4_RX_DMA_EventEnable             DISABLE
#define MX_UART4_RX_DMA_SyncEnable              DISABLE
#define MX_UART4_RX_DMA_DMA_Handle              
#define MX_UART4_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_RX_DMA_SyncSignalID            
#define MX_UART4_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART4_TX */
#define MX_UART4_TX_DMA_Instance                DMA1_Stream1
#define MX_UART4_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_TX_DMA_Priority                DMA_PRIORITY_MEDIUM
#define MX_UART4_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_TX_DMA_SyncRequestNumber       1
#define MX_UART4_TX_DMA_Request                 DMA_REQUEST_UART4_TX
#define MX_UART4_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART4_TX_DMA_SignalID                
#define MX_UART4_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_TX_DMA_IpInstance              
#define MX_UART4_TX_DMA_RequestNumber           1
#define MX_UART4_TX_DMA_EventEnable             DISABLE
#define MX_UART4_TX_DMA_SyncEnable              DISABLE
#define MX_UART4_TX_DMA_DMA_Handle              
#define MX_UART4_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_TX_DMA_SyncSignalID            
#define MX_UART4_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART4_IRQn */
#define MX_UART4_IRQn_interruptPremptionPriority 0
#define MX_UART4_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART4_IRQn_Subriority                0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB14 */
#define MX_PB14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB14_Pin                             PB14
#define MX_PB14_GPIOx                           GPIOB
#define MX_PB14_PinState                        GPIO_PIN_RESET
#define MX_PB14_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD3_RED                              PB14
#define MX_PB14_GPIO_Pin                        GPIO_PIN_14
#define MX_PB14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA15 */
#define MX_PA15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PA15_Pin                             PA15
#define MX_PA15_GPIOx                           GPIOA
#define MX_PA15_PinState                        GPIO_PIN_RESET
#define MX_PA15_GPIO_PuPd                       GPIO_NOPULL
#define MX_STBY                                 PA15
#define MX_PA15_GPIO_Pin                        GPIO_PIN_15
#define MX_PA15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PG7 */
#define MX_PG7_Pin                              PG7
#define MX_PG7_GPIOx                            GPIOG
#define MX_PG7_GPIO_PuPd                        GPIO_PULLDOWN
#define MX_PG7_GPIO_Pin                         GPIO_PIN_7
#define MX_PG7_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_FALLING

/* Pin PC3_C */
#define MX_PC3_C_GPIO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_PC3_C_Pin                            PC3_C
#define MX_PC3_C_GPIOx                          GPIOC
#define MX_PC3_C_PinState                       GPIO_PIN_RESET
#define MX_PC3_C_GPIO_PuPd                      GPIO_NOPULL
#define MX_EN_K                                 PC3_C
#define MX_PC3_C_GPIO_Pin                       GPIO_PIN_3
#define MX_PC3_C_GPIO_ModeDefaultOutputPP       GPIO_MODE_OUTPUT_PP

/* Pin PB7 */
#define MX_PB7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB7_Pin                              PB7
#define MX_PB7_GPIOx                            GPIOB
#define MX_PB7_PinState                         GPIO_PIN_RESET
#define MX_PB7_GPIO_PuPd                        GPIO_NOPULL
#define MX_LD2_BLUE                             PB7
#define MX_PB7_GPIO_Pin                         GPIO_PIN_7
#define MX_PB7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP
#define MX_PB7_GPIO_FM7                         __NULL

/* Pin PC2_C */
#define MX_PC2_C_GPIO_Speed                     GPIO_SPEED_FREQ_LOW
#define MX_PC2_C_Pin                            PC2_C
#define MX_PC2_C_GPIOx                          GPIOC
#define MX_PC2_C_PinState                       GPIO_PIN_RESET
#define MX_PC2_C_GPIO_PuPd                      GPIO_NOPULL
#define MX_IN_K                                 PC2_C
#define MX_PC2_C_GPIO_Pin                       GPIO_PIN_2
#define MX_PC2_C_GPIO_ModeDefaultOutputPP       GPIO_MODE_OUTPUT_PP

/* Pin PD3 */
#define MX_PD3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD3_Pin                              PD3
#define MX_PD3_GPIOx                            GPIOD
#define MX_PD3_PinState                         GPIO_PIN_RESET
#define MX_PD3_GPIO_PuPd                        GPIO_NOPULL
#define MX_RESET                                PD3
#define MX_PD3_GPIO_Pin                         GPIO_PIN_3
#define MX_PD3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

